name: "Build and push Ignition container image"

env:
  NAME: "ignition"
  REGISTRY: "ghcr.io/trusted-execution-clusters"

on:
  push:
    branches:
      - main
    paths:
      - 'containerfiles/ignition.container'
      - '.github/workflows/build-ignition-image.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'containerfiles/ignition.container'
      - '.github/workflows/build-ignition-image.yml'
  schedule:
    - cron:  '0 0 * * MON'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

# Prevent multiple workflow runs from racing to ensure that pushes are made
# sequentially for the main branch. Also cancel in progress workflow runs for
# pull requests only.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build-ignition-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - tag: fedora
            base: fedora:rawhide
          - tag: centos-stream
            base: quay.io/centos/centos:stream9
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule') && github.ref == 'refs/heads/main' && github.repository_owner == 'trusted-execution-clusters'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate image metadata
        id: meta
        run: |
          BUILD_DATE=$(date +%Y%m%d)
          SHORT_SHA=${GITHUB_SHA::7}
          echo "build-date=${BUILD_DATE}" >> $GITHUB_OUTPUT
          echo "version=${{ matrix.tag }}-${BUILD_DATE}-${SHORT_SHA}" >> $GITHUB_OUTPUT

      - name: Build and push Ignition image (${{ matrix.tag }})
        uses: docker/build-push-action@v5
        with:
          context: containerfiles
          file: containerfiles/ignition.container
          build-args: |
            BASE=${{ matrix.base }}
          push: ${{ (github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule') && github.ref == 'refs/heads/main' && github.repository_owner == 'trusted-execution-clusters' }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.NAME }}:${{ matrix.tag }}
            ${{ env.REGISTRY }}/${{ env.NAME }}:${{ steps.meta.outputs.version }}
          platforms: linux/amd64
