name: "Build and push Ignition container image"

env:
  NAME: "ignition"
  REGISTRY: "quay.io/trusted-execution-clusters"

on:
  push:
    branches:
      - main
    paths:
      - 'containerfiles/ignition.container'
      - '.github/workflows/build-ignition-image.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'containerfiles/ignition.container'
      - '.github/workflows/build-ignition-image.yml'
  schedule:
    - cron:  '0 0 * * MON'
  workflow_dispatch:

permissions: read-all

# Prevent multiple workflow runs from racing to ensure that pushes are made
# sequentially for the main branch. Also cancel in progress workflow runs for
# pull requests only.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build-ignition-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - tag: fedora
            base: fedora:rawhide
          - tag: centos-stream
            base: quay.io/centos/centos:stream9
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest commit from ignition repo
        id: get-upstream-commit
        run: |
          UPSTREAM_SHA=$(git ls-remote https://github.com/coreos/ignition.git HEAD | cut -f1)
          SHORT_SHA=$(echo $UPSTREAM_SHA | cut -c1-7)
          echo "sha=${UPSTREAM_SHA}" >> $GITHUB_OUTPUT
          echo "short_sha=${SHORT_SHA}" >> $GITHUB_OUTPUT

      - name: Generate image tag
        id: generate-tag
        run: |
          TAG="${{ matrix.tag }}-${{ steps.get-upstream-commit.outputs.short_sha }}"
          echo "tag=${TAG}" >> $GITHUB_OUTPUT

      - name: Build ignition image (${{ matrix.tag }})
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.NAME }}
          tags: ${{ steps.generate-tag.outputs.tag }}
          containerfiles: |
            containerfiles/ignition.container
          context: containerfiles
          oci: true
          build-args: |
            BASE=${{ matrix.base }}
            COMMIT=${{ steps.get-upstream-commit.outputs.sha }}

      - name: Push ignition image (${{ matrix.tag }}) to registry
        uses: redhat-actions/push-to-registry@v2
        if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule') && github.ref == 'refs/heads/main' && github.repository_owner == 'trusted-execution-clusters'
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.generate-tag.outputs.tag }}
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
